### ISSUE TITLE
Building wheel for pybm3d (setup.py) ... error

### ISSUE THREAD

**Issue by amitsoniR** [ericmjonas/pybm3d#19]
Unable to install package pybm3d... I am getting the error during installation..

>pip install pybm3d
Collecting pybm3d
  Using cached pybm3d-0.2.1.tar.gz (1.1 MB)
Requirement already satisfied: setuptools>=18.0 in c:\users\amit\anaconda3\lib\site-packages (from pybm3d) (54.2.0)
Requirement already satisfied: cython>=0.27 in c:\users\amit\anaconda3\lib\site-packages (from pybm3d) (0.29.21)
Requirement already satisfied: numpy>=1.13 in c:\users\amit\anaconda3\lib\site-packages (from pybm3d) (1.19.5)
Building wheels for collected packages: pybm3d
  Building wheel for pybm3d (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\amit\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\AMIT\\AppData\\Local\\Temp\\pip-install-b8is0xpi\\pybm3d_a8555608938a494f92fee08bece358a5\\setup.py'"'"'; __file__='"'"'C:\\Users\\AMIT\\AppData\\Local\\Temp\\pip-install-b8is0xpi\\pybm3d_a8555608938a494f92fee08bece358a5\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\AMIT\AppData\Local\Temp\pip-wheel-ampnbymf'
       cwd: C:\Users\AMIT\AppData\Local\Temp\pip-install-b8is0xpi\pybm3d_a8555608938a494f92fee08bece358a5\
  Complete output (45 lines):
  c:\users\amit\anaconda3\lib\site-packages\setuptools\dist.py:642: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
    warnings.warn(
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.8
  creating build\lib.win-amd64-3.8\pybm3d
  copying pybm3d\__init__.py -> build\lib.win-amd64-3.8\pybm3d
  running build_ext
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\AMIT\AppData\Local\Temp\pip-install-b8is0xpi\pybm3d_a8555608938a494f92fee08bece358a5\setup.py", line 128, in <module>
      setup(
    File "c:\users\amit\anaconda3\lib\site-packages\setuptools\__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "c:\users\amit\anaconda3\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "c:\users\amit\anaconda3\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "c:\users\amit\anaconda3\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "c:\users\amit\anaconda3\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "c:\users\amit\anaconda3\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\amit\anaconda3\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "c:\users\amit\anaconda3\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "c:\users\amit\anaconda3\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\amit\anaconda3\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "c:\users\amit\anaconda3\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
      _build_ext.run(self)
    File "c:\users\amit\anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
      _build_ext.build_ext.run(self)
    File "c:\users\amit\anaconda3\lib\distutils\command\build_ext.py", line 340, in run
      self.build_extensions()
    File "C:\Users\AMIT\AppData\Local\Temp\pip-install-b8is0xpi\pybm3d_a8555608938a494f92fee08bece358a5\setup.py", line 23, in build_extensions
      self.customize_compiler_for_c_args_and_nvcc()
    File "C:\Users\AMIT\AppData\Local\Temp\pip-install-b8is0xpi\pybm3d_a8555608938a494f92fee08bece358a5\setup.py", line 49, in customize_compiler_for_c_args_and_nvcc
      default_compiler_so = self.compiler.compiler_so
  AttributeError: 'MSVCCompiler' object has no attribute 'compiler_so'
  ----------------------------------------
  ERROR: Failed building wheel for pybm3d
  Running setup.py clean for pybm3d
Failed to build pybm3d
Installing collected packages: pybm3d
    Running setup.py install for pybm3d ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\amit\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\AMIT\\AppData\\Local\\Temp\\pip-install-b8is0xpi\\pybm3d_a8555608938a494f92fee08bece358a5\\setup.py'"'"'; __file__='"'"'C:\\Users\\AMIT\\AppData\\Local\\Temp\\pip-install-b8is0xpi\\pybm3d_a8555608938a494f92fee08bece358a5\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\AMIT\AppData\Local\Temp\pip-record-epe3n2v0\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\amit\anaconda3\Include\pybm3d'
         cwd: C:\Users\AMIT\AppData\Local\Temp\pip-install-b8is0xpi\pybm3d_a8555608938a494f92fee08bece358a5\
    Complete output (47 lines):
    c:\users\amit\anaconda3\lib\site-packages\setuptools\dist.py:642: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
      warnings.warn(
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.8
    creating build\lib.win-amd64-3.8\pybm3d
    copying pybm3d\__init__.py -> build\lib.win-amd64-3.8\pybm3d
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\AMIT\AppData\Local\Temp\pip-install-b8is0xpi\pybm3d_a8555608938a494f92fee08bece358a5\setup.py", line 128, in <module>
        setup(
      File "c:\users\amit\anaconda3\lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\amit\anaconda3\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\amit\anaconda3\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\users\amit\anaconda3\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\amit\anaconda3\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\users\amit\anaconda3\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "c:\users\amit\anaconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\amit\anaconda3\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\amit\anaconda3\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "c:\users\amit\anaconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\amit\anaconda3\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\amit\anaconda3\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
        _build_ext.run(self)
      File "c:\users\amit\anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "c:\users\amit\anaconda3\lib\distutils\command\build_ext.py", line 340, in run
        self.build_extensions()
      File "C:\Users\AMIT\AppData\Local\Temp\pip-install-b8is0xpi\pybm3d_a8555608938a494f92fee08bece358a5\setup.py", line 23, in build_extensions
        self.customize_compiler_for_c_args_and_nvcc()
      File "C:\Users\AMIT\AppData\Local\Temp\pip-install-b8is0xpi\pybm3d_a8555608938a494f92fee08bece358a5\setup.py", line 49, in customize_compiler_for_c_args_and_nvcc
        default_compiler_so = self.compiler.compiler_so
    AttributeError: 'MSVCCompiler' object has no attribute 'compiler_so'
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\amit\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\AMIT\\AppData\\Local\\Temp\\pip-install-b8is0xpi\\pybm3d_a8555608938a494f92fee08bece358a5\\setup.py'"'"'; __file__='"'"'C:\\Users\\AMIT\\AppData\\Local\\Temp\\pip-install-b8is0xpi\\pybm3d_a8555608938a494f92fee08bece358a5\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\AMIT\AppData\Local\Temp\pip-record-epe3n2v0\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\amit\anaconda3\Include\pybm3d' Check the logs for full command output.

**Comment by Diyorazh** [comment]
same issue here!

`ERROR: Command errored out with exit status 1: /opt/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/wd/3nz9vclj4q7gqk8wcrnfynpr0000gn/T/pip-install-n1v8ikx5/pybm3d/setup.py'"'"'; __file__='"'"'/private/var/folders/wd/3nz9vclj4q7gqk8wcrnfynpr0000gn/T/pip-install-n1v8ikx5/pybm3d/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/wd/3nz9vclj4q7gqk8wcrnfynpr0000gn/T/pip-record-jz4841dj/install-record.txt --single-version-externally-managed --compile --install-headers /opt/anaconda3/include/python3.7m/pybm3d Check the logs for full command output.`

**Comment by RikuAlter** [comment]
This is not supposed to work on Windows, only on Linux and OSX. The "compiler_so" field is usable under unix distributions. 
Therefore, you cannot use this pybm3d package to apply bm3d on your image. You can use the bm3d package though https://pypi.org/project/bm3d/ if that works for you.
